routes/web.php
<?php

use App\Http\Controllers\Admin\PostsController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[PostsController::class,'index'])->middleware('auth');

Route::get('login', [LoginController::class, 'view'])->name('login.view');
Route::post('login', [LoginController::class, 'login'])->name('login.check');
Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::resource('posts', PostsController::class);
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

/**
 *
 * Relations:
 * @property User author
 *
 * @property string thumbnail
 */
class Post extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;

    protected $guarded = ['id'];

    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getThumbnailAttribute()
    {
       return optional($this->loadMissing('media')->getFirstMedia())->getUrl('thumbnail');
    }

    public function getImageAttribute()
    {
       return $this->loadMissing('media')->getFirstMediaUrl() ?? null;
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumbnail')
            ->width(100)
            ->height(100);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 *
 * Relations:
 * @property Post[] posts
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    public function posts()
    {
        return $this->hasMany(Post::class, 'user_id');
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Post\CreateRequest;
use App\Http\Requests\Post\UpdateRequest;
use App\Models\Post;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index(): View
    {
        $posts = Post::with('author')->get();
        return view('admin.posts.list', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(): View
    {
        $this->authorize(Post::class,'create');
        return view('admin.posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request): RedirectResponse
    {
        $this->authorize(Post::class,'create');
        $post = Post::create([
            'user_id' => Auth::id(),
            'title'   => $request->input('title'),
            'content' => $request->input('content'),
        ]);
        $post->addMedia($request->file('img'))
            ->preservingOriginal()
            ->toMediaCollection();
        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return View
     */
    public function show(int $id): View
    {
        $post = Post::with('media')->findOrFail($id);
        return view('admin.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return View
     */
    public function edit(int $id): View
    {
        $this->authorize(Post::class,'update');
        $post = Post::with('media')->findOrFail($id);
        return view('admin.posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(UpdateRequest $request, int $id): RedirectResponse
    {
        $this->authorize(Post::class,'update');
        $post = Post::findOrFail($id);
        $post->fill($request->validated())->save();
        if ($request->has('img')) {
            $post->addMedia($request->file('img'))
                ->preservingOriginal()
                ->toMediaCollection();
        }
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy(int $id): Response
    {
        $this->authorize(Post::class,'delete');
        $post = Post::findOrFail($id);
        $post->delete();
        return \Illuminate\Support\Facades\Response::make('مطلب با موفقیت حذف گردید');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/Delete.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Delete extends Component
{
    public $route;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($route)
    {
        $this->route = $route;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.delete');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card-title">
        <h4>ایجاد مطلب</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="basic-form p-10">
                    @include('partials.errors')
                    @include('partials.success')
                    <form method="post" enctype="multipart/form-data" action="{{ route('posts.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="title">عنوان مطلب</label>
                            <input id="title" name="title" type="text"
                                   class="form-control input-default hasPersianPlaceHolder"
                            >
                        </div>
                        <div class="form-group">
                            <label for="content">محتوا</label>
                            <input id="content" name="content" type="text"
                                   class="form-control input-default hasPersianPlaceHolder"
                            >
                        </div>

                        <div class="form-group">
                            <label for="file">تصویر مطلب</label>
                            <input type="file" id="img" name="img">
                        </div>
                        <div class="form-group m-t-20">
                            <button type="submit" class="btn btn-primary m-b-10 m-l-5">ثبت اطلاعات
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card-title">
        <h4>ویرایش مطلب</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="basic-form p-10">
                    @include('partials.errors')
                    @include('partials.success')
                    <form method="post" enctype="multipart/form-data" action="{{ route('posts.update',[$post->id]) }}">
                        @csrf
                        <input name="_method" type="hidden" value="PUT">
                        <div class="form-group">
                            <label for="title">عنوان مطلب</label>
                            <input id="title" name="title" type="text"
                                   class="form-control input-default hasPersianPlaceHolder"
                                   value="{{ old('title',$post->title )  }}"
                            >
                        </div>
                        <div class="form-group">
                            <label for="content">محتوا</label>
                            <input id="content" name="content" type="text"
                                   class="form-control input-default hasPersianPlaceHolder"
                                   value="{{old('content',$post->content ) }}"
                            >
                        </div>

                        <div class="form-group">
                            <label for="logo">تصویر مطلب</label>
                            <input type="file" name="img">
                            @if(isset($post->thumbnail))
                                <img src="{{$post->thumbnail}}" alt="تصویر" height="100" width="100">
                            @else ---
                            @endif
                        </div>
                        <div class="form-group m-t-20">
                            <button type="submit" class="btn btn-primary m-b-10 m-l-5">ثبت اطلاعات
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/list.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card-title">
        <h4>لیست مطالب </h4>
    </div>
    <div class="card-body">
        @include('partials.success')
        @include('partials.errors')
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>نویسنده</th>
                    <th>عنوان</th>
                    <th> عملیات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($posts as $post)
                    <tr>
                        <th scope="row">{{ $post->id }}</th>
                        <td>{{ $post->author->name }}</td>
                        <td>{{ $post->title }}</td>
                        <td>

                            <a href="{{ route('posts.show',[$post->id]) }}">
                                <i class="fa fa-eye"></i>
                            </a>

                            @can('update', App\Models\Post::class)
                                <a href="{{ route('posts.edit',[$post->id]) }}">
                                    <i class="fa fa-edit"></i>
                                </a>
                            @endcan
                            @can('delete', App\Models\Post::class)
                                <x-delete route="posts.destroy">{{$post->id}}</x-delete>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/posts/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card-title">
        <h4>مشاهده مطلب</h4>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="basic-form p-10">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="title">عنوان مطلب</label>
                            <input id="title" name="title" type="text"
                                   class="form-control input-default hasPersianPlaceHolder"
                                   value="{{ $post->title  }}"
                            >
                        </div>
                        <div class="form-group">
                            <label for="content">محتوا</label>
                            <input id="content" name="content" type="text"
                                   class="form-control input-default hasPersianPlaceHolder"
                                   value="{{$post->content }}"
                            >
                        </div>

                        <div class="form-group">
                            <label for="logo">تصویر مطلب</label>
                            @if(isset($post->thumbnail))
                                <img src="{{$post->thumbnail}}" alt="تصویر" height="100" width="100">
                            @else ---
                            @endif
                        </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon.png">
    <title>blog</title>
    <link href="/css/lib/bootstrap/bootstrap-rtl.min.css" rel="stylesheet">
    <link href="/css/helper.css" rel="stylesheet">
    <link href="/css/fonts.css" rel="stylesheet">
    <link href="/css/admin/style.css" rel="stylesheet">
    <!--CK editor -->
    <link href="/css/lib/ckeditor/plugins/contents.css" rel="stylesheet">
    <!--DataTable -->
    {{--    <link rel="stylesheet" type="text/css" href="/datatables/css/datatables.min.css">--}}
    <link rel="stylesheet" type="text/css" href="/datatables/css/jquery.dataTables.min2.css">
    <link rel="stylesheet" type="text/css" href="/datatables/css/select.dataTables.min.css">

    <link rel="stylesheet" type="text/css" href="/datatables/css/dataTables.checkboxes.css">
    <!--select2 -->
    <link href="/js/lib/select2/select2.min.css" rel="stylesheet"/>
    <!--font awesome-->
    <link href="/fontawesome/css/all.css" rel="stylesheet"/>
    <!--modal image-->
    <link href="/css/lib/modal-image.css" rel="stylesheet"/>
    <!--Persian Date Picker-->
    <link href="/css/lib/persianDatePicker/persian-datepicker.min.css" rel="stylesheet"/>
    <style>
        ul {
        }

        li {
        }

        ul li > ul {
            margin-right: 10px;
        }
    </style>
</head>
<body>
<!-- Preloader - style you can find in spinners.css -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
    </svg>
</div>
<!-- Main wrapper  -->
<div id="main-wrapper">
    <!-- header header  -->
    <div class="header">
        <nav class="navbar top-navbar navbar-expand-md navbar-light">
            <!-- Logo -->
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <!-- Logo icon -->
                    <b><img src="/images/logo.png" alt="homepage" class="dark-logo"/></b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span>وبلاگ</span>
                </a>
            </div>
            <!-- End Logo -->
            <div class="navbar-collapse">
                <!-- toggle and nav items -->

                <!-- User profile and search -->

            </div>
            <ul class="dropdown-user">
                <li><a href="{{ route('logout') }}"><i class="fa fa-power-off"></i> خروج</a></li>
            </ul>
        </nav>
    </div>
    <!-- End header header -->
    <!-- Left Sidebar  -->
    <div class="right-sidebar">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="nav-devider"></li>
                    <li class="nav-label"></li>


                    <li><a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-book"></i><span
                                class="hide-menu">مطالب
                        </span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="{{route('posts.index')}}">لیست مطالب</a></li>
                            @can('create', App\Models\Post::class)
                                <li><a href="{{route('posts.create')}}">مطلب جدید</a></li>
                            @endcan
                        </ul>
                    </li>

                </ul>

            </nav>

            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </div>
    <!-- End Left Sidebar  -->
    <!-- Page wrapper  -->
    <div class="page-wrapper">

        <!-- Container fluid  -->
        <div class="container-fluid">
            <!-- Start Page Content -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        @yield('content')
                    </div>
                </div>
            </div>
            <!-- /# row -->
            <!-- End PAge Content -->
        </div>
        <!-- End Container fluid  -->
    </div>
    <!-- End Page wrapper  -->
</div>
<!-- End Wrapper -->

<script src="/js/lib/jquery/jquery.min.js"></script>

<!-- Bootstrap tether Core JavaScript -->
<script src="/js/lib/bootstrap/js/popper.min.js"></script>
<script src="/js/lib/bootstrap/js/bootstrap.min.js"></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src="/js/jquery.slimscroll.js"></script>
<!--Menu sidebar -->
<script src="/js/sidebarmenu.js"></script>
<!--CK editor -->
<script src="/js/lib/ckeditor/ckeditor.js"></script>

<!--stickey kit -->
<script src="/js/lib/sticky-kit-master/dist/sticky-kit.min.js"></script>
<script src="/js/lib/select2/select2.min.js"></script>
<!--Custom JavaScript -->
<script src="/js/custom.min.js"></script>
<!--DataTables -->
{{--<script type="text/javascript" charset="utf8" src="/datatables/js/datatables.min.js"></script>--}}
<script type="text/javascript" charset="utf8" src="/datatables/js/jquery.dataTables.min2.js"></script>
<script type="text/javascript" charset="utf8" src="/datatables/js/dataTables.select.min.js"></script>
<script type="text/javascript" charset="utf8" src="/datatables/js/dataTables.checkboxes.min.js"></script>
<!--Create Jquery Post Request -->
<script src="/js/lib/jquery-postback/jquery-postback.js"></script>
<!--Persian Date Picker -->
<script src="/js/lib/persianDatePicker/persian-date.min.js"></script>
<script src="/js/lib/persianDatePicker/persian-datepicker.min.js"></script>
@stack('scripts')

</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'وبلاگ') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        وبلاگ
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login.view') }}">ورود</a></li>
{{--                            <li><a href="{{ route('register') }}">ثبت نام</a></li>--}}

                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ \Illuminate\Support\Facades\Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">

                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            خروج
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/partials/errors.blade.php
@if($errors->any())
<div class="alert alert-danger">
    @foreach($errors->all() as $error)
    <p>{{ $error }}</p>
    @endforeach
</div>
@endif

resources/views/partials/success.blade.php
@if(session('status'))
    <div class="alert alert-success">
        <p>{{ session('status') }}</p>
    </div>
@endif